/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardRegistrarRouteImport } from './routes/dashboard/registrar'
import { Route as DashboardFacultyRouteImport } from './routes/dashboard/faculty'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student.index'
import { Route as DashboardRegistrarIndexRouteImport } from './routes/dashboard/registrar.index'
import { Route as DashboardFacultyIndexRouteImport } from './routes/dashboard/faculty.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin.index'
import { Route as DashboardStudentScheduleRouteImport } from './routes/dashboard/student.schedule'
import { Route as DashboardStudentGradesRouteImport } from './routes/dashboard/student.grades'
import { Route as DashboardStudentEnrollmentRouteImport } from './routes/dashboard/student.enrollment'
import { Route as DashboardStudentAttendanceRouteImport } from './routes/dashboard/student.attendance'
import { Route as DashboardRegistrarTranscriptsRouteImport } from './routes/dashboard/registrar.transcripts'
import { Route as DashboardRegistrarSubjectsRouteImport } from './routes/dashboard/registrar.subjects'
import { Route as DashboardRegistrarStudentsRouteImport } from './routes/dashboard/registrar.students'
import { Route as DashboardRegistrarReportsRouteImport } from './routes/dashboard/registrar.reports'
import { Route as DashboardRegistrarRegistrationsRouteImport } from './routes/dashboard/registrar.registrations'
import { Route as DashboardRegistrarReenrollmentRouteImport } from './routes/dashboard/registrar.reenrollment'
import { Route as DashboardRegistrarRecordsRouteImport } from './routes/dashboard/registrar.records'
import { Route as DashboardRegistrarProfileRouteImport } from './routes/dashboard/registrar.profile'
import { Route as DashboardRegistrarFacultyRouteImport } from './routes/dashboard/registrar.faculty'
import { Route as DashboardRegistrarEnrollmentRouteImport } from './routes/dashboard/registrar.enrollment'
import { Route as DashboardRegistrarCurriculumRouteImport } from './routes/dashboard/registrar.curriculum'
import { Route as DashboardRegistrarAnnouncementsRouteImport } from './routes/dashboard/registrar.announcements'
import { Route as DashboardFacultySubjectsRouteImport } from './routes/dashboard/faculty.subjects'
import { Route as DashboardFacultySubjectDetailsRouteImport } from './routes/dashboard/faculty.subject-details'
import { Route as DashboardFacultyProfileRouteImport } from './routes/dashboard/faculty.profile'
import { Route as DashboardFacultyPerformanceRouteImport } from './routes/dashboard/faculty.performance'
import { Route as DashboardFacultyGradesRouteImport } from './routes/dashboard/faculty.grades'
import { Route as DashboardFacultyClassesRouteImport } from './routes/dashboard/faculty.classes'
import { Route as DashboardFacultyAttendanceRouteImport } from './routes/dashboard/faculty.attendance'
import { Route as DashboardFacultyAnnouncementsRouteImport } from './routes/dashboard/faculty.announcements'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin.users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin.settings'
import { Route as DashboardAdminSecurityRouteImport } from './routes/dashboard/admin.security'
import { Route as DashboardAdminAnnouncementsRouteImport } from './routes/dashboard/admin.announcements'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrarRoute = DashboardRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacultyRoute = DashboardFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardRegistrarIndexRoute = DashboardRegistrarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRegistrarRoute,
} as any)
const DashboardFacultyIndexRoute = DashboardFacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardStudentScheduleRoute =
  DashboardStudentScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentGradesRoute = DashboardStudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentEnrollmentRoute =
  DashboardStudentEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentAttendanceRoute =
  DashboardStudentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardRegistrarTranscriptsRoute =
  DashboardRegistrarTranscriptsRouteImport.update({
    id: '/transcripts',
    path: '/transcripts',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarSubjectsRoute =
  DashboardRegistrarSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarStudentsRoute =
  DashboardRegistrarStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarReportsRoute =
  DashboardRegistrarReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarRegistrationsRoute =
  DashboardRegistrarRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarReenrollmentRoute =
  DashboardRegistrarReenrollmentRouteImport.update({
    id: '/reenrollment',
    path: '/reenrollment',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarRecordsRoute =
  DashboardRegistrarRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarProfileRoute =
  DashboardRegistrarProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarFacultyRoute =
  DashboardRegistrarFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarEnrollmentRoute =
  DashboardRegistrarEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarCurriculumRoute =
  DashboardRegistrarCurriculumRouteImport.update({
    id: '/curriculum',
    path: '/curriculum',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardRegistrarAnnouncementsRoute =
  DashboardRegistrarAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardRegistrarRoute,
  } as any)
const DashboardFacultySubjectsRoute =
  DashboardFacultySubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardFacultySubjectDetailsRoute =
  DashboardFacultySubjectDetailsRouteImport.update({
    id: '/subject-details',
    path: '/subject-details',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardFacultyProfileRoute = DashboardFacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardFacultyPerformanceRoute =
  DashboardFacultyPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardFacultyGradesRoute = DashboardFacultyGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardFacultyClassesRoute = DashboardFacultyClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardFacultyRoute,
} as any)
const DashboardFacultyAttendanceRoute =
  DashboardFacultyAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardFacultyAnnouncementsRoute =
  DashboardFacultyAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardFacultyRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSecurityRoute = DashboardAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnnouncementsRoute =
  DashboardAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/faculty': typeof DashboardFacultyRouteWithChildren
  '/dashboard/registrar': typeof DashboardRegistrarRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/announcements': typeof DashboardFacultyAnnouncementsRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/faculty/grades': typeof DashboardFacultyGradesRoute
  '/dashboard/faculty/performance': typeof DashboardFacultyPerformanceRoute
  '/dashboard/faculty/profile': typeof DashboardFacultyProfileRoute
  '/dashboard/faculty/subject-details': typeof DashboardFacultySubjectDetailsRoute
  '/dashboard/faculty/subjects': typeof DashboardFacultySubjectsRoute
  '/dashboard/registrar/announcements': typeof DashboardRegistrarAnnouncementsRoute
  '/dashboard/registrar/curriculum': typeof DashboardRegistrarCurriculumRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/faculty': typeof DashboardRegistrarFacultyRoute
  '/dashboard/registrar/profile': typeof DashboardRegistrarProfileRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/reenrollment': typeof DashboardRegistrarReenrollmentRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/reports': typeof DashboardRegistrarReportsRoute
  '/dashboard/registrar/students': typeof DashboardRegistrarStudentsRoute
  '/dashboard/registrar/subjects': typeof DashboardRegistrarSubjectsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/faculty/': typeof DashboardFacultyIndexRoute
  '/dashboard/registrar/': typeof DashboardRegistrarIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/announcements': typeof DashboardFacultyAnnouncementsRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/faculty/grades': typeof DashboardFacultyGradesRoute
  '/dashboard/faculty/performance': typeof DashboardFacultyPerformanceRoute
  '/dashboard/faculty/profile': typeof DashboardFacultyProfileRoute
  '/dashboard/faculty/subject-details': typeof DashboardFacultySubjectDetailsRoute
  '/dashboard/faculty/subjects': typeof DashboardFacultySubjectsRoute
  '/dashboard/registrar/announcements': typeof DashboardRegistrarAnnouncementsRoute
  '/dashboard/registrar/curriculum': typeof DashboardRegistrarCurriculumRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/faculty': typeof DashboardRegistrarFacultyRoute
  '/dashboard/registrar/profile': typeof DashboardRegistrarProfileRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/reenrollment': typeof DashboardRegistrarReenrollmentRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/reports': typeof DashboardRegistrarReportsRoute
  '/dashboard/registrar/students': typeof DashboardRegistrarStudentsRoute
  '/dashboard/registrar/subjects': typeof DashboardRegistrarSubjectsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/faculty': typeof DashboardFacultyIndexRoute
  '/dashboard/registrar': typeof DashboardRegistrarIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/faculty': typeof DashboardFacultyRouteWithChildren
  '/dashboard/registrar': typeof DashboardRegistrarRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/faculty/announcements': typeof DashboardFacultyAnnouncementsRoute
  '/dashboard/faculty/attendance': typeof DashboardFacultyAttendanceRoute
  '/dashboard/faculty/classes': typeof DashboardFacultyClassesRoute
  '/dashboard/faculty/grades': typeof DashboardFacultyGradesRoute
  '/dashboard/faculty/performance': typeof DashboardFacultyPerformanceRoute
  '/dashboard/faculty/profile': typeof DashboardFacultyProfileRoute
  '/dashboard/faculty/subject-details': typeof DashboardFacultySubjectDetailsRoute
  '/dashboard/faculty/subjects': typeof DashboardFacultySubjectsRoute
  '/dashboard/registrar/announcements': typeof DashboardRegistrarAnnouncementsRoute
  '/dashboard/registrar/curriculum': typeof DashboardRegistrarCurriculumRoute
  '/dashboard/registrar/enrollment': typeof DashboardRegistrarEnrollmentRoute
  '/dashboard/registrar/faculty': typeof DashboardRegistrarFacultyRoute
  '/dashboard/registrar/profile': typeof DashboardRegistrarProfileRoute
  '/dashboard/registrar/records': typeof DashboardRegistrarRecordsRoute
  '/dashboard/registrar/reenrollment': typeof DashboardRegistrarReenrollmentRoute
  '/dashboard/registrar/registrations': typeof DashboardRegistrarRegistrationsRoute
  '/dashboard/registrar/reports': typeof DashboardRegistrarReportsRoute
  '/dashboard/registrar/students': typeof DashboardRegistrarStudentsRoute
  '/dashboard/registrar/subjects': typeof DashboardRegistrarSubjectsRoute
  '/dashboard/registrar/transcripts': typeof DashboardRegistrarTranscriptsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/enrollment': typeof DashboardStudentEnrollmentRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/schedule': typeof DashboardStudentScheduleRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/faculty/': typeof DashboardFacultyIndexRoute
  '/dashboard/registrar/': typeof DashboardRegistrarIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/announcements'
    | '/dashboard/faculty'
    | '/dashboard/registrar'
    | '/dashboard/student'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/announcements'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/faculty/grades'
    | '/dashboard/faculty/performance'
    | '/dashboard/faculty/profile'
    | '/dashboard/faculty/subject-details'
    | '/dashboard/faculty/subjects'
    | '/dashboard/registrar/announcements'
    | '/dashboard/registrar/curriculum'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/faculty'
    | '/dashboard/registrar/profile'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/reenrollment'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/reports'
    | '/dashboard/registrar/students'
    | '/dashboard/registrar/subjects'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/attendance'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin/'
    | '/dashboard/faculty/'
    | '/dashboard/registrar/'
    | '/dashboard/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/announcements'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/announcements'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/faculty/grades'
    | '/dashboard/faculty/performance'
    | '/dashboard/faculty/profile'
    | '/dashboard/faculty/subject-details'
    | '/dashboard/faculty/subjects'
    | '/dashboard/registrar/announcements'
    | '/dashboard/registrar/curriculum'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/faculty'
    | '/dashboard/registrar/profile'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/reenrollment'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/reports'
    | '/dashboard/registrar/students'
    | '/dashboard/registrar/subjects'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/attendance'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/registrar'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/announcements'
    | '/dashboard/faculty'
    | '/dashboard/registrar'
    | '/dashboard/student'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/faculty/announcements'
    | '/dashboard/faculty/attendance'
    | '/dashboard/faculty/classes'
    | '/dashboard/faculty/grades'
    | '/dashboard/faculty/performance'
    | '/dashboard/faculty/profile'
    | '/dashboard/faculty/subject-details'
    | '/dashboard/faculty/subjects'
    | '/dashboard/registrar/announcements'
    | '/dashboard/registrar/curriculum'
    | '/dashboard/registrar/enrollment'
    | '/dashboard/registrar/faculty'
    | '/dashboard/registrar/profile'
    | '/dashboard/registrar/records'
    | '/dashboard/registrar/reenrollment'
    | '/dashboard/registrar/registrations'
    | '/dashboard/registrar/reports'
    | '/dashboard/registrar/students'
    | '/dashboard/registrar/subjects'
    | '/dashboard/registrar/transcripts'
    | '/dashboard/student/attendance'
    | '/dashboard/student/enrollment'
    | '/dashboard/student/grades'
    | '/dashboard/student/schedule'
    | '/dashboard/admin/'
    | '/dashboard/faculty/'
    | '/dashboard/registrar/'
    | '/dashboard/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrar': {
      id: '/dashboard/registrar'
      path: '/registrar'
      fullPath: '/dashboard/registrar'
      preLoaderRoute: typeof DashboardRegistrarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faculty': {
      id: '/dashboard/faculty'
      path: '/faculty'
      fullPath: '/dashboard/faculty'
      preLoaderRoute: typeof DashboardFacultyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/registrar/': {
      id: '/dashboard/registrar/'
      path: '/'
      fullPath: '/dashboard/registrar/'
      preLoaderRoute: typeof DashboardRegistrarIndexRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/faculty/': {
      id: '/dashboard/faculty/'
      path: '/'
      fullPath: '/dashboard/faculty/'
      preLoaderRoute: typeof DashboardFacultyIndexRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/student/schedule': {
      id: '/dashboard/student/schedule'
      path: '/schedule'
      fullPath: '/dashboard/student/schedule'
      preLoaderRoute: typeof DashboardStudentScheduleRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/grades': {
      id: '/dashboard/student/grades'
      path: '/grades'
      fullPath: '/dashboard/student/grades'
      preLoaderRoute: typeof DashboardStudentGradesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/enrollment': {
      id: '/dashboard/student/enrollment'
      path: '/enrollment'
      fullPath: '/dashboard/student/enrollment'
      preLoaderRoute: typeof DashboardStudentEnrollmentRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/attendance': {
      id: '/dashboard/student/attendance'
      path: '/attendance'
      fullPath: '/dashboard/student/attendance'
      preLoaderRoute: typeof DashboardStudentAttendanceRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/registrar/transcripts': {
      id: '/dashboard/registrar/transcripts'
      path: '/transcripts'
      fullPath: '/dashboard/registrar/transcripts'
      preLoaderRoute: typeof DashboardRegistrarTranscriptsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/subjects': {
      id: '/dashboard/registrar/subjects'
      path: '/subjects'
      fullPath: '/dashboard/registrar/subjects'
      preLoaderRoute: typeof DashboardRegistrarSubjectsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/students': {
      id: '/dashboard/registrar/students'
      path: '/students'
      fullPath: '/dashboard/registrar/students'
      preLoaderRoute: typeof DashboardRegistrarStudentsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/reports': {
      id: '/dashboard/registrar/reports'
      path: '/reports'
      fullPath: '/dashboard/registrar/reports'
      preLoaderRoute: typeof DashboardRegistrarReportsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/registrations': {
      id: '/dashboard/registrar/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrar/registrations'
      preLoaderRoute: typeof DashboardRegistrarRegistrationsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/reenrollment': {
      id: '/dashboard/registrar/reenrollment'
      path: '/reenrollment'
      fullPath: '/dashboard/registrar/reenrollment'
      preLoaderRoute: typeof DashboardRegistrarReenrollmentRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/records': {
      id: '/dashboard/registrar/records'
      path: '/records'
      fullPath: '/dashboard/registrar/records'
      preLoaderRoute: typeof DashboardRegistrarRecordsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/profile': {
      id: '/dashboard/registrar/profile'
      path: '/profile'
      fullPath: '/dashboard/registrar/profile'
      preLoaderRoute: typeof DashboardRegistrarProfileRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/faculty': {
      id: '/dashboard/registrar/faculty'
      path: '/faculty'
      fullPath: '/dashboard/registrar/faculty'
      preLoaderRoute: typeof DashboardRegistrarFacultyRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/enrollment': {
      id: '/dashboard/registrar/enrollment'
      path: '/enrollment'
      fullPath: '/dashboard/registrar/enrollment'
      preLoaderRoute: typeof DashboardRegistrarEnrollmentRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/curriculum': {
      id: '/dashboard/registrar/curriculum'
      path: '/curriculum'
      fullPath: '/dashboard/registrar/curriculum'
      preLoaderRoute: typeof DashboardRegistrarCurriculumRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/registrar/announcements': {
      id: '/dashboard/registrar/announcements'
      path: '/announcements'
      fullPath: '/dashboard/registrar/announcements'
      preLoaderRoute: typeof DashboardRegistrarAnnouncementsRouteImport
      parentRoute: typeof DashboardRegistrarRoute
    }
    '/dashboard/faculty/subjects': {
      id: '/dashboard/faculty/subjects'
      path: '/subjects'
      fullPath: '/dashboard/faculty/subjects'
      preLoaderRoute: typeof DashboardFacultySubjectsRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/subject-details': {
      id: '/dashboard/faculty/subject-details'
      path: '/subject-details'
      fullPath: '/dashboard/faculty/subject-details'
      preLoaderRoute: typeof DashboardFacultySubjectDetailsRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/profile': {
      id: '/dashboard/faculty/profile'
      path: '/profile'
      fullPath: '/dashboard/faculty/profile'
      preLoaderRoute: typeof DashboardFacultyProfileRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/performance': {
      id: '/dashboard/faculty/performance'
      path: '/performance'
      fullPath: '/dashboard/faculty/performance'
      preLoaderRoute: typeof DashboardFacultyPerformanceRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/grades': {
      id: '/dashboard/faculty/grades'
      path: '/grades'
      fullPath: '/dashboard/faculty/grades'
      preLoaderRoute: typeof DashboardFacultyGradesRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/classes': {
      id: '/dashboard/faculty/classes'
      path: '/classes'
      fullPath: '/dashboard/faculty/classes'
      preLoaderRoute: typeof DashboardFacultyClassesRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/attendance': {
      id: '/dashboard/faculty/attendance'
      path: '/attendance'
      fullPath: '/dashboard/faculty/attendance'
      preLoaderRoute: typeof DashboardFacultyAttendanceRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/faculty/announcements': {
      id: '/dashboard/faculty/announcements'
      path: '/announcements'
      fullPath: '/dashboard/faculty/announcements'
      preLoaderRoute: typeof DashboardFacultyAnnouncementsRouteImport
      parentRoute: typeof DashboardFacultyRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/announcements': {
      id: '/dashboard/admin/announcements'
      path: '/announcements'
      fullPath: '/dashboard/admin/announcements'
      preLoaderRoute: typeof DashboardAdminAnnouncementsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminAnnouncementsRoute: typeof DashboardAdminAnnouncementsRoute
  DashboardAdminSecurityRoute: typeof DashboardAdminSecurityRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminAnnouncementsRoute: DashboardAdminAnnouncementsRoute,
  DashboardAdminSecurityRoute: DashboardAdminSecurityRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardFacultyRouteChildren {
  DashboardFacultyAnnouncementsRoute: typeof DashboardFacultyAnnouncementsRoute
  DashboardFacultyAttendanceRoute: typeof DashboardFacultyAttendanceRoute
  DashboardFacultyClassesRoute: typeof DashboardFacultyClassesRoute
  DashboardFacultyGradesRoute: typeof DashboardFacultyGradesRoute
  DashboardFacultyPerformanceRoute: typeof DashboardFacultyPerformanceRoute
  DashboardFacultyProfileRoute: typeof DashboardFacultyProfileRoute
  DashboardFacultySubjectDetailsRoute: typeof DashboardFacultySubjectDetailsRoute
  DashboardFacultySubjectsRoute: typeof DashboardFacultySubjectsRoute
  DashboardFacultyIndexRoute: typeof DashboardFacultyIndexRoute
}

const DashboardFacultyRouteChildren: DashboardFacultyRouteChildren = {
  DashboardFacultyAnnouncementsRoute: DashboardFacultyAnnouncementsRoute,
  DashboardFacultyAttendanceRoute: DashboardFacultyAttendanceRoute,
  DashboardFacultyClassesRoute: DashboardFacultyClassesRoute,
  DashboardFacultyGradesRoute: DashboardFacultyGradesRoute,
  DashboardFacultyPerformanceRoute: DashboardFacultyPerformanceRoute,
  DashboardFacultyProfileRoute: DashboardFacultyProfileRoute,
  DashboardFacultySubjectDetailsRoute: DashboardFacultySubjectDetailsRoute,
  DashboardFacultySubjectsRoute: DashboardFacultySubjectsRoute,
  DashboardFacultyIndexRoute: DashboardFacultyIndexRoute,
}

const DashboardFacultyRouteWithChildren =
  DashboardFacultyRoute._addFileChildren(DashboardFacultyRouteChildren)

interface DashboardRegistrarRouteChildren {
  DashboardRegistrarAnnouncementsRoute: typeof DashboardRegistrarAnnouncementsRoute
  DashboardRegistrarCurriculumRoute: typeof DashboardRegistrarCurriculumRoute
  DashboardRegistrarEnrollmentRoute: typeof DashboardRegistrarEnrollmentRoute
  DashboardRegistrarFacultyRoute: typeof DashboardRegistrarFacultyRoute
  DashboardRegistrarProfileRoute: typeof DashboardRegistrarProfileRoute
  DashboardRegistrarRecordsRoute: typeof DashboardRegistrarRecordsRoute
  DashboardRegistrarReenrollmentRoute: typeof DashboardRegistrarReenrollmentRoute
  DashboardRegistrarRegistrationsRoute: typeof DashboardRegistrarRegistrationsRoute
  DashboardRegistrarReportsRoute: typeof DashboardRegistrarReportsRoute
  DashboardRegistrarStudentsRoute: typeof DashboardRegistrarStudentsRoute
  DashboardRegistrarSubjectsRoute: typeof DashboardRegistrarSubjectsRoute
  DashboardRegistrarTranscriptsRoute: typeof DashboardRegistrarTranscriptsRoute
  DashboardRegistrarIndexRoute: typeof DashboardRegistrarIndexRoute
}

const DashboardRegistrarRouteChildren: DashboardRegistrarRouteChildren = {
  DashboardRegistrarAnnouncementsRoute: DashboardRegistrarAnnouncementsRoute,
  DashboardRegistrarCurriculumRoute: DashboardRegistrarCurriculumRoute,
  DashboardRegistrarEnrollmentRoute: DashboardRegistrarEnrollmentRoute,
  DashboardRegistrarFacultyRoute: DashboardRegistrarFacultyRoute,
  DashboardRegistrarProfileRoute: DashboardRegistrarProfileRoute,
  DashboardRegistrarRecordsRoute: DashboardRegistrarRecordsRoute,
  DashboardRegistrarReenrollmentRoute: DashboardRegistrarReenrollmentRoute,
  DashboardRegistrarRegistrationsRoute: DashboardRegistrarRegistrationsRoute,
  DashboardRegistrarReportsRoute: DashboardRegistrarReportsRoute,
  DashboardRegistrarStudentsRoute: DashboardRegistrarStudentsRoute,
  DashboardRegistrarSubjectsRoute: DashboardRegistrarSubjectsRoute,
  DashboardRegistrarTranscriptsRoute: DashboardRegistrarTranscriptsRoute,
  DashboardRegistrarIndexRoute: DashboardRegistrarIndexRoute,
}

const DashboardRegistrarRouteWithChildren =
  DashboardRegistrarRoute._addFileChildren(DashboardRegistrarRouteChildren)

interface DashboardStudentRouteChildren {
  DashboardStudentAttendanceRoute: typeof DashboardStudentAttendanceRoute
  DashboardStudentEnrollmentRoute: typeof DashboardStudentEnrollmentRoute
  DashboardStudentGradesRoute: typeof DashboardStudentGradesRoute
  DashboardStudentScheduleRoute: typeof DashboardStudentScheduleRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentAttendanceRoute: DashboardStudentAttendanceRoute,
  DashboardStudentEnrollmentRoute: DashboardStudentEnrollmentRoute,
  DashboardStudentGradesRoute: DashboardStudentGradesRoute,
  DashboardStudentScheduleRoute: DashboardStudentScheduleRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardFacultyRoute: typeof DashboardFacultyRouteWithChildren
  DashboardRegistrarRoute: typeof DashboardRegistrarRouteWithChildren
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardFacultyRoute: DashboardFacultyRouteWithChildren,
  DashboardRegistrarRoute: DashboardRegistrarRouteWithChildren,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
